apiVersion: v1
kind: Service
metadata:
  name: argocd-app-service
spec:
  selector:
    app.kubernetes.io/name: argocd-app
  type: Nodeport
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: argocd-app-deployment
spec:
  replicas: 3
  selector:
    matchLabels:
      app.kubernetes.io/name: argocd-app
  template:
    metadata:
      labels:
        app.kubernetes.io/name: argocd-app
    spec:
      containers:
        - name: argocd-app-container
          image: dp00615/app-with-argocd:773075c5267ea21f21e3651193b082e03c726c98
          ports:
            - protocol: TCP
              containerPort: 8080
